version: '3.8'
services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    env_file: .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
        - minio_data:/data
    ports:
        - "9000:9000"  # MinIO API
        - "9001:9001"  # MinIO Console
    restart: unless-stopped

volumes:
    minio_data: