services:
  hello-world-app:
    build:
      context: .
      dockerfile: docker/Dockerfile.helloworld
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
      - frontend_node_modules:/app/frontend/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped

volumes:
  frontend_node_modules: