services:
  hello-world-app:
    build:
      context: .
      dockerfile: docker/Dockerfile.helloworld
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped