spring:
  application:
    name: auth-service

  jackson:
    default-property-inclusion: non_null
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/auth_service}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: create-drop
token:
  signing:
    key: ${JWT_SIGNING_KEY:defaultSigningKey12345678901234567890123412341234123412341234123412341234}


logging:
  level:
    olsh.backend.authservice: debug

springdoc:
  default-produces-media-type: application/json
  api-docs:
    version: openapi_3_0
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger
    enabled: true
