spring:
  application:
    name: auth-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jackson:
    default-property-inclusion: non_null
  grpc:
    server:
      port: ${GRPC_PORT:9092}
      reflection:
        enabled: true

server:
  port: ${PORT:8081}

token:
  signing:
    key: ${JWT_SIGNING_KEY:defaultSigningKey12345678901234567890123412341234123412341234123412341234}
  access:
    expiration: ${ACCESS_TOKEN_EXPIRATION:144000000} # 24 hours in milliseconds
  refresh:
    expiration: ${REFRESH_TOKEN_EXPIRATION:1008000000} # 7 days in milliseconds

grpc:
  users-service:
    host: ${USERS_SERVICE_HOST:localhost}
    port: ${USERS_SERVICE_PORT:9093}

logging:
  level:
    olsh.backend.authservice: ${LOG_LEVEL:INFO}

springdoc:
  default-produces-media-type: application/json
  api-docs:
    version: openapi_3_0
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger
    enabled: true
    operations-sorter: method

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true
    java:
      enabled: true
    build:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
