services:
  feedback-service:
    build: .
    ports:
      - "9090:9090"  # gRPC server
    environment:
      - GRPC_PORT=9090
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=feedback_user
      - DB_PASSWORD=feedback_password
      - DB_NAME=feedback_db
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=feedback
      - MINIO_USE_SSL=false
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=feedback_db
      - POSTGRES_USER=feedback_user
      - POSTGRES_PASSWORD=feedback_password
    healthcheck:
      test: pg_isready -U feedback_user -d feedback_db
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
    volumes:
      - minio-data:/data
    restart: unless-stopped

volumes:
  postgres-data:
  minio-data: