# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import marimo_executor_service_pb2 as marimo__executor__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in marimo_executor_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MarimoExecutorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartSession = channel.unary_unary(
                '/marimo.MarimoExecutor/StartSession',
                request_serializer=marimo__executor__service__pb2.StartSessionRequest.SerializeToString,
                response_deserializer=marimo__executor__service__pb2.StartSessionResponse.FromString,
                _registered_method=True)
        self.ExecuteCell = channel.unary_unary(
                '/marimo.MarimoExecutor/ExecuteCell',
                request_serializer=marimo__executor__service__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=marimo__executor__service__pb2.ExecuteResponse.FromString,
                _registered_method=True)
        self.EndSession = channel.unary_unary(
                '/marimo.MarimoExecutor/EndSession',
                request_serializer=marimo__executor__service__pb2.EndSessionRequest.SerializeToString,
                response_deserializer=marimo__executor__service__pb2.EndSessionResponse.FromString,
                _registered_method=True)
        self.GetSessionState = channel.unary_unary(
                '/marimo.MarimoExecutor/GetSessionState',
                request_serializer=marimo__executor__service__pb2.SessionStateRequest.SerializeToString,
                response_deserializer=marimo__executor__service__pb2.SessionStateResponse.FromString,
                _registered_method=True)
        self.UpdateWidgetValue = channel.unary_unary(
                '/marimo.MarimoExecutor/UpdateWidgetValue',
                request_serializer=marimo__executor__service__pb2.UpdateWidgetValueRequest.SerializeToString,
                response_deserializer=marimo__executor__service__pb2.UpdateWidgetValueResponse.FromString,
                _registered_method=True)


class MarimoExecutorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCell(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateWidgetValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarimoExecutorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartSession': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSession,
                    request_deserializer=marimo__executor__service__pb2.StartSessionRequest.FromString,
                    response_serializer=marimo__executor__service__pb2.StartSessionResponse.SerializeToString,
            ),
            'ExecuteCell': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCell,
                    request_deserializer=marimo__executor__service__pb2.ExecuteRequest.FromString,
                    response_serializer=marimo__executor__service__pb2.ExecuteResponse.SerializeToString,
            ),
            'EndSession': grpc.unary_unary_rpc_method_handler(
                    servicer.EndSession,
                    request_deserializer=marimo__executor__service__pb2.EndSessionRequest.FromString,
                    response_serializer=marimo__executor__service__pb2.EndSessionResponse.SerializeToString,
            ),
            'GetSessionState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionState,
                    request_deserializer=marimo__executor__service__pb2.SessionStateRequest.FromString,
                    response_serializer=marimo__executor__service__pb2.SessionStateResponse.SerializeToString,
            ),
            'UpdateWidgetValue': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateWidgetValue,
                    request_deserializer=marimo__executor__service__pb2.UpdateWidgetValueRequest.FromString,
                    response_serializer=marimo__executor__service__pb2.UpdateWidgetValueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marimo.MarimoExecutor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marimo.MarimoExecutor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MarimoExecutor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marimo.MarimoExecutor/StartSession',
            marimo__executor__service__pb2.StartSessionRequest.SerializeToString,
            marimo__executor__service__pb2.StartSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCell(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marimo.MarimoExecutor/ExecuteCell',
            marimo__executor__service__pb2.ExecuteRequest.SerializeToString,
            marimo__executor__service__pb2.ExecuteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marimo.MarimoExecutor/EndSession',
            marimo__executor__service__pb2.EndSessionRequest.SerializeToString,
            marimo__executor__service__pb2.EndSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marimo.MarimoExecutor/GetSessionState',
            marimo__executor__service__pb2.SessionStateRequest.SerializeToString,
            marimo__executor__service__pb2.SessionStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateWidgetValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marimo.MarimoExecutor/UpdateWidgetValue',
            marimo__executor__service__pb2.UpdateWidgetValueRequest.SerializeToString,
            marimo__executor__service__pb2.UpdateWidgetValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
