version: '3.8'
name: 'article-service'
services:
  articles-minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    env_file: .env
    container_name: ${CONTAINER_MINIO}
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
        - minio_data:/data
    networks:
        - grpc-network
    ports:
        - "9000:9000"  # MinIO API
        - "9001:9001"  # MinIO Console
    restart: unless-stopped

  articles-db:
    image: postgres:latest
    env_file: .env
    container_name: ${CONTAINER_POSTGRES}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    volumes:
      - postgres_data_articles:/var/lib/postgresql/data
    networks:
      - grpc-network
    ports:
      - "${POSTGRES_PORT}:5432"

  article-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: article-service
    env_file: .env
    environment:
      - SERVICE_HOST=${SERVICE_HOST}
      - SERVICE_PORT=${SERVICE_PORT}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_NAME=${POSTGRES_NAME}
    depends_on:
      - articles-db
      - articles-minio
    volumes:
      - ./files:/app/files
    networks:
      - grpc-network
    ports:
      - "50051:50051"
    restart: unless-stopped

volumes:
  postgres_data_articles:
  minio_data:

networks:
    grpc-network: