version: '3.8'
name: 'article-service'
services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    env_file: .env
    container_name: ${CONTAINER_MINIO}
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
        - minio_data:/data
    networks:
        - grpc-network
    ports:
        - "9000:9000"  # MinIO API
        - "9001:9001"  # MinIO Console
    restart: unless-stopped

  articles-db:
    image: postgres:latest
    env_file: .env
    container_name: ${CONTAINER_DB}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data_articles:/var/lib/postgresql/data
    networks:
      - grpc-network
    ports:
      - "${DB_PORT}:5432"

  article-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: article-service
    env_file: .env
    depends_on:
      - db
      - minio
    volumes:
      - ./files:/app/files
    networks:
      - grpc-network
    ports:
      - "50051:50051"
    restart: unless-stopped

volumes:
  postgres_data_articles:
  minio_data:

networks:
    grpc-network:
      external: true