DROP TABLE IF EXISTS labs CASCADE;
DROP TABLE IF EXISTS submissions CASCADE;
DROP TABLE IF EXISTS article_relations CASCADE;
DROP TABLE IF EXISTS lab_assets CASCADE;
DROP TABLE IF EXISTS submission_assets CASCADE;