CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    created_at TIMESTAMP,
    last_login_at TIMESTAMP,
    labs_solved INT NOT NULL DEFAULT 0,
    labs_reviewed INT NOT NULL DEFAULT 0,
    balance INT NOT NULL DEFAULT 10
); 