name: Debug Project IDs

on:
  push:

jobs:
  get-project-ids:
    runs-on: ubuntu-latest
    steps:
      - name: Get Project Fields
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          script: |
            const query = `
              query {
                organization(login: "IU-Capstone-Project-2025") {
                  projectV2(number: 6) {
                    id
                    title
                    fields(first: 20) {
                      nodes {
                        ... on ProjectV2Field {
                          id
                          name
                          __typename
                        }
                        ... on ProjectV2SingleSelectField {
                          id
                          name
                          __typename
                          options {
                            id
                            name
                          }
                        }
                      }
                    }
                  }
                }
              }
            `;
            
            try {
              const result = await github.graphql(query);
              console.log("=== PROJECT FIELDS ===");
              console.log(JSON.stringify(result, null, 2));
              
              const fields = result.organization.projectV2.fields.nodes;
              
              for (const field of fields) {
                if (field.name === "Status" && field.options) {
                  console.log("=== STATUS FIELD FOUND ===");
                  console.log(`STATUS_FIELD_ID: "${field.id}"`);
                  
                  for (const option of field.options) {
                    console.log(`${option.name.toUpperCase()}_OPTION_ID: "${option.id}"`);
                  }
                }
              }
            } catch (error) {
              console.error("Error:", error);
            } 