name: CD - Deploy to Server

on:
  workflow_dispatch:
    inputs:
      services:
        description: 'Comma-separated list of services to deploy (e.g., api-gateway,auth-service). Leave empty to deploy all.'
        required: false
        default: ''

  # pull_request:
  #   branches:
  #     - main
  #     - dev
  
  push:
    branches:
      - '**' # Deploy all branches, MUST BE DELETED BEFORE MERGING TO MAIN

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy services
        run: |
          chmod +x ./scripts/deploy_green.sh
          # Convert comma-separated list to space-separated list
          services_to_deploy=$(echo ${{ github.event.inputs.services }} | tr ',' ' ')
          ./scripts/deploy_green.sh $services_to_deploy