name: Service Tests

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
        - "*"

jobs:
  test-java-services:
    strategy:
      matrix:
        service: [api-gateway, users-service, auth-service]
    runs-on: ubuntu-latest
    name: Test ${{ matrix.service }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run tests
        working-directory: ./services/${{ matrix.service }}
        run: ./gradlew test

  test-labs-service:
    runs-on: ubuntu-latest
    name: Test labs-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: ./services/labs-service
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests
        working-directory: ./services/labs-service
        run: pytest 